bootlin/elixir

README.md, lib.py, query.py, script.sh, update.py
=> Small fixes

data.py, script.sh, update.py
=> Filenames that contain spaces are now processed correctly

data.py, lib.py, update.py
Signed-off-by: Priit Laes <plaes@plaes.org>
=> Clean up unused imports

README.md
This project is awesome but its installation is a bit obscure, so I rewrite the installation manual.
Signed-off-by: Hao Lee <haolee.swjtu@gmail.com>
=> Rewrite installation document

http/web.py
=> Set Pygments option to keep leading blank lines

http/web.py, query.py
Refactored for now only the ident command.
After this is approved we can go and change the other queries one by one to eliminate the regexes.
I might add some more documentation / small style fixes but you can already review it and comment so I could fix. 
Thanks!
=> Refactored ident query to use python objects rather than parsing REs

http/web.py
=> URL-encode the query string when redirecting an ident search

README.md
Add distro specific configuration information.
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
=> Documentation: Update Ubuntu/Debian specific config

README.md, query.py
Implemented CMD interface for ident and file.
I can implement the rest of the command if you'd like. Let's start with this and see if there are comments to address.
=> Implemented query cmd commands for ident and file

http/web.py
Sample config for lighthttpd:
```
server.document-root = server_root + "/elixir/http"
url.redirect = ( "^/$" => "/linux/latest/source" )
url.rewrite  = ( "^/.*/(source|ident|search)" =>  "/web.py/$1")
setenv.add-environment = ( "PYTHONIOENCODING" => "utf-8",
"LXR_PROJ_DIR" => "/path/to/elixir-data" )
```
=> Support for lighthttpd CGI

api/api.py
=> Return empty lists when no identifier found

.travis.yml, data.py, query.py
Hi,
Following @cxw42 work to write tests I think it's time to add a proper CI (continuous integration) as a merge check.
This will reduce the amount of manual work to check every PR, and will continue to reduce with every new added test.
@michaelopdenacker You will need to follow the first 3 steps [here](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci).
The CI's only action other than setting up the environment is running the "prove" command.
I have checked that the CI fails when there is a bug on the first commit and this [run](https://travis-ci.com/github/carmeli-tamir/elixir/builds/152280920), and CI success on the final success on this [run](https://travis-ci.com/github/carmeli-tamir/elixir/builds/152694714)
=> Add travis ci

README.md
Added a cute little box indicating CI status of the master branch
=> Added CI status

t/api_test.py
1. Testing results for existing identifiers. 
2. Testing version parameter options.
=> Added more API tests

.travis.yml, api/api.py, t/200-api.t
- Upgrade the CI machine to bionic (Ubuntu 18.04)
- Fix the broken CI
=> Adding python3-pytest to CI dependencies

utils/speedtest.py
This solves issue https://github.com/bootlin/elixir/issues/109
This script can be used with every project and with any number of
versions, files or identifiers.
=> Add database performance test script

http/filters/makefiledir.py, http/filters/makefileo.py
This fix different problems I have seen in the makefiles
=> Fix makefile filters

http/filters/common.py, http/filters/configin.py, http/filters/cppinc.py, http/filters/cpppathinc.py, http/filters/dtsi.py, http/filters/ident.py, http/filters/kconfig.py, http/filters/makefiledir.py, http/filters/makefiledtb.py, http/filters/makefilefile.py, http/filters/makefileo.py, http/filters/makefilesubdir.py, lib.py
Encode filters numbers into letters to avoid conflicts with pygments
+ Some code simplification and blacklist addition
=> Fix filters

.mailmap, .travis.yml, README.adoc, api/api.py, data.py, find-file-doc-comments.pl, http/web.py, query.py, script.sh, t/100-basic.t, t/TestHelpers.pm, t/api_test.py, update.py, utils/index-all-repositories, utils/pack-repositories, utils/speedtest.py, utils/update-elixir-data
These are some miscellaneous changes to tidy the code and history ahead of the next release.  No functional changes.
Let me know if I picked the wrong authoritative emails for the mailmap --- I'm happy to change it!
Thanks for considering this PR!
=> Copyright statements, mailmap, and whitespace

.travis.yml, api/api.py, http/web.py, t/.gitignore, t/050-testhelpers.t, t/100-basic.t, t/400-web.t, t/TestEnvironment.pm, t/TestHelpers.pm, t/api_test.py, t/interact.pl
- Fixes #78 
- Does not fix #134 
- Builds on #133.  Only the commits starting with https://github.com/bootlin/elixir/commit/16fc8e541753117c994f387a2091d1bbe58e58d9 are new in this PR.  The others are in #133.  See [this diff](https://github.com/bootlin/elixir/pull/135/files/299f762fdf8c8146a54ce3c14927599de388944d..53bce3913f2f8f146d9678c582ac549d1a53a928) for just the new changes in this PR.
This PR adds:
- a few tests of web.py
- tests of the new doc-comment reporting
- doc-comment reporting through web.py
:tada: 
Comments welcome!
=> Doc comments: frontend

t/100-basic.t, t/tree/issue131.h
This adds a file and a test to detect the issue reported in #131
=> Add tests of `struct class` (#131)

data.py, script.sh
This is needed to fix https://github.com/bootlin/elixir/issues/61
=> Enable ctags extern variable support

http/img/arrow-dropdown-16.svg, http/style.css, http/web.py, query.py, templates/layout.html
+ Change select style to match the global theme
+ Add an option to search in all file families and make it default
+ Add a tooltip on the search select to explains what it does
=> Improve Elixir UI

script.sh, t/100-basic.t, t/tree/arch/arm/xen/hypercall.S, t/tree/drivers/firmware/broadcom/bcm74xx_sprom.c, t/tree/issue150.S
Ask and ye shall receive ;) .
Fixes #150.
Passes all tests on my system.  However, as you know, the existing tests are nowhere near exhaustive.  Please test on your own before merging.  (And add any test cases you use to the existing suite! ;) )
=> Detect function definitions in .S files

utils/index-all-repositories
This is needed for old linux versions
=> index-all-repositories : Fetch all tags

data.py, http/web.py, lib.py, query.py, update.py
- Some database clean up
- Some code clean up
- Allow some strange idents like $$divI
- Fix some problems with quoted idents
=> Various fixes and clean ups

http/web.py
This implement https://github.com/bootlin/elixir/issues/160
=> web.py: Link to the first occurence in ident concise display

projects/grub.sh, utils/index-all-repositories, utils/update-elixir-data
This implement https://github.com/bootlin/elixir/issues/162
=> Add Grub support

api/api.py, t/api_test.py
The documentation can be useful even when requesting though the api so we should add it ^^
=> api: Add documentation in api results

README.adoc, docker/centos/Dockerfile, docker/debian/Dockerfile
Docker files needs to be updated to work properly with Elixir 2.1 since we have made a lot of changes since Elixir 1.0
/!\ This hasn't been tested
Related to https://github.com/bootlin/elixir/issues/172
=> Update docker files for Elixir 2.1

http/web.py, lib.py
/!\ I can't test it yet so be careful with that
=> Fix issues #175 and #176

projects/optee.sh, utils/index-all-repositories, utils/update-elixir-data
Please note that I wasn't able to actually test it. But I've tested the list_tags_h() function, though.
=> Add optee support

README.adoc
To fix issues like #213, configure for SELinux
is necessary.
Signed-off-by: anatasluo <luolongjuna@gmail.com>
=> README: add configure step for SELinux and systemd

http/dynamic-references.js, http/filters/defconfig.py, http/filters/dtscompB.py, http/filters/dtscompC.py, http/filters/dtscompD.py, http/filters/ident.py, http/filters/kconfigidents.py, http/style.css, templates/layout.html
=> Add a mode that displays a popup on identifier click instead of redirecting to another URL

http/dynamic-references.js, templates/layout.html
* Change style.css version to force stylesheet reload
* Fix documentation links rendering
=> Minor JS popup fixes

projects/xen.sh
This PR is to add support for indexing the Xen hypervisor and the core library and utilities in the xen.git repository.
=> Support for Xen

http/banner.css, http/style.css
so that the sidebar stays on the screen when a file with very long lines is scrolled to the end.
Deployed on https://elixir.ksi.ii.uj.edu.pl
=> Make the main element as wide as the code

http/dynamic-references.js
Fixes a bug, that sometimes causes confusing behavior if two identifiers are clicked, and the first identifier loads after the second one.
To reproduce:
1. Find a file that contains an identifier with a long list of references (good examples: `true`, `continue`, `switch`, although cache might cause the list of references to load too fast for this to work)
2. Click the identifier, and then, while the first identifier is still loading, click another one (preferably with a shorter list of references, so that the popup for the second identifier will load before the popup for the first identifier)
There is a high chance that the popup for the second identifier will load and then disappear to be replaced by a popup for the first identifier. This patch aims to fix that behavior.
I have deployed …
=> Cancel a loading popup if another identificator is clicked

http/web.py, templates/ident.html, templates/topbar.html
Fixes #309, both manual search and display in search bar.
=> Quick fix for searching identifiers with commas

http/script.js, http/style.css, http/web.py, templates/layout.html, templates/sidebar.html
~~Note: based on falcon-wsgi and increase-tablet-mode-min-width, check the last commit~~
=> Reduce sidebar flashing

elixir/web.py
This allows Jinja to cache templates between requests.
The performance improvement is non-negligible for requests where the majority of time is spent in Jinja. PR with versions cache is upcoming.
=> web: Make Jinja environment global for app

elixir/web.py
Note: based on global-jinja-env
=> web: Add versions cache

elixir/web.py, static/style.css, templates/layout.html, templates/source.html
=> Add a 'download file' link in footer

elixir/web.py
to make DT compatibles work again...
=> web: Fix identifier unquoting
