- http/header.css
- http/script.js
- http/style.css
- templates/layout.html
Refactor css to use `position: sticky` instead of javascript-based fixed elements (topnav and sidebar),
using a mobile-first approach (probably more future proof and maintainable).
Pros:
- horizontal scroll will not move the header and fixed elements
- should fix laggy scrolling in Firefox ESR mentioned by @pokazef
- line-numbers always visibles during horizontal scroll (chrome only for now)
- scrolling in tablet and mobile side-menu doesn't scroll the main page anymore
Cons:
- [bad support for old browsers](http://caniuse.com/#feat=css-sticky), but degrade gracefully (fixed elements just scroll)
- required to change line jump internals, but it should behave the same
> Use mobile-first approach and sticky positioning

- README.md
- script.sh
This PR adds support to Elixir for the Zephyr Project, a Linux Foundation Project (see https://www.zephyrproject.org for more information). The Zephyr Project has much in common with Linux and could benefit from having its source code indexed by Elixir in the same manner as Linux, Busybox and Das U-Boot.
The `zephyr-vx.y.z` tags are technically redundant and filtered out as discussed in zephyrproject-rtos/zephyr#1420.
> Add support for the Zephyr project.

- query.py
- update.py
Include C++ files when indexing and tokenizing files.
Unfortunately due to how C++ utilizes namespaces and classes, depending
on your code base, this currently introduces a large amount of false positives
for unqualified identifiers that look the same.
> Add basic support for C++ files

- lib.py
On machines with Python < 3.5, subprocess.run is not available. In this
case, subprocess.check_output serves the same purpose [1].
This allows Elixir to run on older systems, such as Ubuntu 14.04 which
comes with Python 3.4.
[1] https://docs.python.org/3.5/library/subprocess.html#subprocess.check_output
Signed-off-by: Chen-Yu Tsai <wens@csie.org>
> Fall back to subprocess.check_output when subprocess.run is not available

- http/banner.css
In narrow view frames the Subtitle would be displayed over the sidebar.
z-index changed to 29 to be one lower than the sidebar: https://github.com/frhun/elixir/blob/3e69f7ddb1f9d58bb348ff34045f97942e0acf7e/http/style.css#L910
> Fixing overlap of banner subtitle with sidebar

- docker/centos/Dockerfile
This PR introduces a working Docker container built on Centos7 Apache 2.4 Openshift base image with Python 3.6.8.
> Openshift image based on centos7

- script.sh
This stops the tokenizer from treating double quotes within single quotes (i.e `'"'`) as the start of a string literal. It looks a bit messy because of the shell quote escaping but it's actually just adding `[^']`.
Fixes #40
> Fix C string literals

- query.py
This patch fixes the error when the query on the tagging
expects 3 levels (v3 v3.1 v3.1-rc0) but gets only one level
from the `script.sh list-tags -h`
This results in the following error:
```
...
/home/naveen/workspace/elixir/query.py in query(cmd='versions', *args=())
53         for line in scriptLines ('list-tags', '-h'):
54             decoded_line = decode(line)
=>   55             topmenu, submenu, tag = decoded_line.split(' ')
56             if db.vers.exists (tag):
57                 if topmenu not in versions:
topmenu undefined, submenu undefined, tag undefined, decoded_line = 'Tag_V1', \
decoded_line.split = <built-in method split of str object>
...
```
Fix the issue by processing the menu levels when applicable.
Signed-off-by: Naveen Kaje <naveen.kaje@juul.com>
> Parse the tag levels when applicable

- README.md
- api/api.py
Implemented a JSON REST api for the 'ident' query.
The REST api is implemented using falcon framework, over mod_wsgi extension for httpd (apache).
I have added instructions in the README for how to install mod_wsgi and how to configure the .conf file in order to make it work. Tell me if you get in trouble, I'll help.
If this PR is merged, I intend to clean the code duplication in web.py and api.py regarding the initialization and usage of query, and also the implement the API for more queries as well.
> Added an api, based on wsgi_mod with falcon framework

- api/api.py
- http/web.py
- lib.py
I'm starting to fix the code duplication between api.py and web.py.
This PR removes the necessity of a call_quey function by fixing a path dependency in lib.py.
> Fixed path dependency in lib.py

- README.md
The Linux-kernel GitHub repo referenced in README doesn't have tags for sublevel (X.Y.Z) releases, unlike the master Bootlin Elixir site.  This confused me while trying to set up a local development instance.  This PR adds the master repo that does have the sublevel tags to the README.  I got the repo URL from <https://config9.com/linux/linux-kernel-how-to-obtain-a-particular-version-right-upto-sublevel/>.
Thank you for considering this PR!
> README: include URL for Linux sublevel tags

- http/web.py
Display filenames and identifiers at the *beginning* of the <title>.
This way, they are better visible in modern browsers' tabs as they
usually cut off the title for space reasons.
This also fixes handling of the root path.
Examples of changed titles:
"Linux source code: (v5.5.6) - Bootlin" becomes "Linux source code (v5.5.6) - Bootlin"
"Linux source code: arch (v5.5.6) - Bootlin" becomes "arch - Linux source code (v5.5.6) - Bootlin"
"Linux source code: arch/um/Makefile (v5.5.6) - Bootlin" becomes "Makefile in arch/um - Linux source code (v5.5.6) - Bootlin"
---
Motivation: I usually have multiple tabs of Elixir open, and all I can read is "Linux source", which makes navigating the tabs really difficult.
> Prepend filename or identifier in HTML <title>

- .editorconfig
- .gitignore
- README.md
- http/banner.css
- script.sh
- templates/header.html
- templates/layout.html
- utils/index-all-repositories
This is a bit of cleanup I noticed a few minutes ago.  Hope it helps!  Let me know if you have any questions or concerns.
- Change the few files that use leading tabs into leading spaces.  This way they match the other files in the repo.
- Add an [EditorConfig](https://editorconfig.org) file so that supported editors will automatically use spaces instead of tabs.  (Note: I am an EditorConfig developer.)
- (Extra) Add some common editor backup-file extensions to .gitignore.
> Regularize whitespace; add editorconfig

- t/TestEnvironment.pm
- t/TestHelpers.pm
- t/interact.pl
Run `./t/interact.pl` and it will build a database from `t/tree` and
leave you in a shell so you can experiment.  When you exit the shell,
the temporary repo and database will be cleaned up.  This script is not run by `prove`, so does not interfere with the automated testing.
Also:
- TestEnvironment: add report() function to produce a human-readable
summary of the environment
- TestHelpers: turn on `strict` and `warnings` so the caller doesn't
have to manually `use strict` and `use warnings`.
> Add t/interact.pl for interactive testing

- api/api.py
- t/100-basic.t
- t/200-api.t
- t/TestHelpers.pm
- t/api_test.py
Added a pytest setup for api.py, currently with just one basic test - after this is approved I'll add some more.
Since the API is based on the Pythonic falcon, and falcon includes it's own testing library, the test is written in Python - but is executed from the existing Perl tests which set up the environment to get Elixir working.
The PR is verified on the CI of my Elixir fork, [link](https://travis-ci.com/github/carmeli-tamir/elixir/builds/154313598). @michaelopdenacker Do you need assistance setting it up?
@cxw42 appreciate your feedback.
> Added API tests

- .gitignore
- api/api.py
- data.py
- find-file-doc-comments.pl
- http/web.py
- query.py
- script.sh
- t/300-doc-comments.t
- t/TestEnvironment.pm
- t/TestHelpers.pm
- t/interact.pl
- update.py
(I will rebase this after some of the other open PRs are merged, but I wanted to post it now to provide an opportunity for feedback.)
This PR adds back-end support for doc-comment extraction (part of #78).  It does not update api.py or web.py.
While reading through the existing Python code, I found a number of the variable names confusing.  For example, in update.py, "blob" isn't a hash; it's a sequential ID that maps to a blob in a particular tag.  I changed some of the variable names to try to reduce confusion for myself and for future readers :) .  I can certainly change them back and add comments if you wish.
In query.py, subcommand `ident` has a loop over blobs to collect all the defs and refs.  I needed to add doc comments to that loop, and took advantage of the opportunity to …
> Extract doc comments - back-end

- find-file-doc-comments.pl
- script.sh
- t/300-doc-comments.t
- t/TestHelpers.pm
- t/tree/issue102.c
If the first function in a file does not have a doc comment, do not
run off the beginning of the file.  Fixes #102.
Also:
- Add t/tree/issue102.c that exhibits this bug.
- in find-file-doc-comments.pl and script.sh, exit with a nonzero code
if this should recur.
> doc-comments: support uncommented first function

- http/web.py
If this test succeed it clears cmd so the next test always leads to an
error 400.
And this code is not used anymore so it's better to remove it.
> http/web.py: Remove broken old code

- README.adoc
- http/web.py
This allow the use of tags with slashes by encoding them in the links and decoding them when needed.
And thus it fix issue https://github.com/bootlin/elixir/issues/106
Apache need a special configuration when we encode slashes in URL so I updated the documentation according to that.
> Encode slashes in URL

- script.sh
This fix the FIXME tag name in the web menus
> script.sh: Specify current dir when including specific project scripts

- query.py
- script.sh
This prevent bad queries when the git repo is more up to date than the database.
> query.py: get latest indexed version instead of latest git version

- README.adoc
The file has been updated to enable Kconfig highlighting for file with
names like Kconfig.x86, Kconfig.debug, Kconfig-nommu, ...
> README: Update informations about pygments installation

- .travis.yml
- README.adoc
- api/api.py
- data.py
- http/filters/barebox.py
- http/filters/commonkconfig.py
- http/filters/coreboot.py
- http/filters/ident.py
- http/filters/kconfig.py
- http/filters/kconfigidents.py
- http/filters/linux.py
- http/filters/makefilekconfig.py
- http/filters/qemu.py
- http/filters/u-boot.py
- http/filters/zephyr.py
- http/style.css
- http/web.py
- lib.py
- query.py
- script.sh
- t/100-basic.t
- t/300-doc-comments.t
- t/api_test.py
- templates/layout.html
- update.py
- utils/speedtest.py
Update database to support Kconfig and Devicetree idents and add the idea of file families.
Update update.py to use 4 threads for faster indexation.
This fix issues : 
- https://github.com/bootlin/elixir/issues/57 because we support Kconfig now.
- https://github.com/bootlin/elixir/issues/101 because update.py uses 4 threads now.
- https://github.com/bootlin/elixir/issues/11 because this has been fixed in ctags.
> Database update

- .travis.yml
- api/api.py
- t/.gitignore
- t/100-basic.t
- t/TestEnvironment.pm
- t/TestHelpers.pm
- t/api_test.py
- t/interact.pl
This implements https://github.com/bootlin/elixir/issues/129#issuecomment-632659022 , among other things.  I have added some explanatory comments on specific lines.
- Update the test infrastructure to create an LXR_PROJ_DIR structure.  This way we can test the http and api interfaces as well as the command-line interface.
- Update api.py to:
- always set LXR_REPO_DIR and LXR_DATA_DIR based on LXR_PROJ_DIR.
- use os.environ as a fallback for req.env
Also:
- add a helper function to the test infrastructure to test web.py.  A later PR will add tests using that function.
- fix a bug in t/interact.pl that could prevent deleting the temporary directory on exit.
- Travis: verbose output from `prove`, for easier failure diagnosis
- Fix a latent bug in t/100 --- when I refactored TestEnvironment, …
> API: Always set LXR_DATA_DIR and LXR_REPO_DIR based on LXR_PROJ_DIR.

- http/filters/ident.py
- http/filters/kconfigidents.py
Fix problems when pigments add an html tag in the __KEEPIDENTS__XX like : 
`</span>__<span class="n">KEEPKCONFIGIDENTS__C</span>`
> filters/*idents.py: Add possible html tag added by pygments

- README.adoc
- script.sh
The parser has been modified before being merged so we adapt to the
changes.
See : https://github.com/universal-ctags/ctags/pull/2553
/!\ NOTE : Merge only when we switch to universal-ctags upstream version /!\
> script.sh: Adapt to universal-ctags Kconfig parser

- lib.py
- script.sh
Enable indexing of struct, enum and union members in Elixir
And adapt blacklist to avoid unneeded stuff
This fix : https://github.com/bootlin/elixir/issues/48
> Enable struct, enum and union members indexing

- README.adoc
- update.py
- utils/index-all-repositories
- utils/update-elixir-data
update.py can now use any number of threads passed as argument (minimum 3)
Without arguments it uses 8 threads.
Threads are distributed between the different functions using the following priority order :
refs > defs > docs
The linux database (without old versions) can now be indexed in 3.5 days (on our server) compared to 5.8 days for the last update.py version.
> Update.py : Improve threading

- README.adoc
- api/api.py
- data.py
- find_compatible_dts.py
- http/filters/common.py
- http/filters/dtscomp.py
- http/filters/dtscompB.py
- http/filters/dtscompC.py
- http/filters/dtscompD.py
- http/web.py
- projects/arm-trusted-firmware.sh
- projects/barebox.sh
- projects/linux.sh
- projects/u-boot.sh
- projects/zephyr.sh
- query.py
- script.sh
- templates/layout.html
- update.py
This implement https://github.com/bootlin/elixir/issues/144
Short log : 
- Add a python script to search DT compatibles in different type of files
- Add 2 new databases, one to index where DT compatibles are defined and used and another to index where they are documented
- Add a special handling in query('ident',..) for DT compatibles
- Use web.py ident page to display DT compatibles, "Define in" for C files, "Documented in" for documentations and "Referenced in" for DT files
- Improve web.py to show references even if there is no definition (because of a missing element in the database or a DT compatible not listed in a C file but only in a DT file)
- Add special filters for DT compatibles
- Add a 'DT compatible' option to search for compatible strings (they are not listed in "All …
> Devicetree compatible properties support

- update.py
This prevent the script from locking at line 578 because UpdateIds will never send an event to wake up the threads (line 91) if there is no tag to add. (Solves https://github.com/bootlin/elixir/issues/155)
Also change len(tag_buf) to num_tags in line 548, no need to compute the
length again as we already have it.
> update.py: Exit if there is no tag to add

- README.adoc
- data.py
- http/autocomplete.css
- http/autocomplete.js
- http/autocomplete.py
- lib.py
- query.py
- script.sh
- templates/layout.html
To do that we use a slightly modified version of the script found here:
https://github.com/autocompletejs/autocomplete.js/tree/2.7
This code is under MIT licence so it's compatible with Elixir's licence.
Autocomplete is active after at least 4 characters are written in the search bar.
There is a delay of 500ms before sending a request to the server to avoid sending requests before you finished to type the query.
This can be modified if needed.
The server answers requests from the script via a new interface:
`https://elixir.bootlin.com/acp?q=<query>&f=<family>&p=<project>`
/!\ Apache configuration needs to be updated /!\
And this is handled by autocomplete.py
The script creates and uses a tmp file to store idents for each project in order to reduce the time needed to answer a request.
This …
> Add autocompletion for ident search bar

- data.py
- lib.py
- query.py
Add a new data and a new lib functions to get the families of a macro and test if it's compatible or not with the requested family.
This doesn't require a new database it only uses the values already present in the database.
This implement https://github.com/bootlin/elixir/issues/145
> queries: Support C macros in DT files

- README.adoc
This PR corrects a small misspelling in the project README. 
Thanks for all of your hard work with elixir!
> Fix a misspelling with the path used to store elixir-data

- find-file-doc-comments.pl
- t/300-doc-comments.t
- t/tree/include/linux/memblock.h
- t/tree/issue134.c
Fixes #134.
- Add test files and test cases
- Look for kernel-doc comments on every symbol we get from our ctags invocations.  This includes at least structs, enums, and macros.
All tests pass on my system.
Happy Hacktoberfest to all! :)
> Extract kernel-doc comments for things besides functions

- find-file-doc-comments.pl
- t/300-doc-comments.t
- t/TestEnvironment.pm
- t/tree/issue186-counterexamples.c
- t/tree/issue186.c
The root cause of #186 was that find-file-doc-comments.pl was not properly checking symbols defined as a macro on one line of a file and as a function earlier in that file.  This PR:
- Adds tests of that situation, both for undocumented symbols (the failure mode in #186) and for documented symbols (for completeness)
- Modifies find-file-doc-comments.pl to always index by line, never by name, so it won't matter if a name is defined multiple times in one file 
- Cleans up verbose output in find-file-doc-comments.pl (but no substantive changes to that output)
- Fixes a typo
Thanks for considering this PR!
> Extract documentation even if a symbol has multiple definitions in the same file (#186)

- find-file-doc-comments.pl
- t/300-doc-comments.t
- t/tree/issue188.c
Fixes #188.
- Support code like
void foo() {
#define whatever
}
- On warning, report the name of the file that triggered it.
> Doc comments: support indented #defines; report filename on warnings

- http/style.css
On some screens / fonts, the link background color is too thick and it hides features of the line above
Before:
After:
> Shrink ".hilight a" background color

- query.py
- t/api_test.py
This sorts the definition buffer by file path and then by type (reversed).
Sorting by type in reverse order allows to have structs definitions before members.
This solves issue https://github.com/bootlin/elixir/issues/189
As a side effect it also lists functions prototypes before functions implementations which is a good thing I guess.
> query: Sort definitions by type

- docker/centos/Dockerfile
- docker/debian/Dockerfile
This allows to have real time logging while building the database.
Without that you have to wait for the end of the script to get the output which can be really long for some projects.
> docker: Execute update.py with unbuffered output

- find-file-doc-comments.pl
- t/300-doc-comments.t
- t/tree/issue192.c
Fixes #192.
Previously, find-file-doc-comments could handle
int foo() {}
but not
int
foo() {}
When processing a function, if the reported line begins with the function's symbol, assume we have the latter situation.  Move backward to the first line that doesn't start with an ASCII letter.  This is my best current guess as to a reasonable heuristic.
Additionally, remove an extra copy of one of our tests --- we were running the same test twice in a row! :)
Thank you for considering this PR!
> find-file-doc-comments: Handle "type\nname" definitions

- http/web.py
This splits definition printing into multiple lists, one for each type.
It allows to find wanted definitions faster when a single name is used for multiple definitions.
It's the implementation of the changes suggested by @tpetazzoni and discussed in issue https://github.com/bootlin/elixir/issues/189
It just changes the way we print information so API and tests are not impacted by those changes.
> web.py : Split defintion list into lists for each type

- docker/centos/Dockerfile
- docker/debian/Dockerfile
Tests are not working in docker for now.
There are multiple issues here.
List of fixed issues for now :
- python3-pytest creates a pytest-3 executable (instead of pytest) so prove can't launch it properly (fixed by a symbolic link)
- git was not configured to create commits (fixed with dummy config)
- some perl packages for tests were missing in centos docker
- git version in centos 7 was too old for the commands used in tests (-C parameter) (fixed by using rh-git218 and creating symlinks to use it as git)
List of remaining issues :
- api tests return a 404 error for each query so prove fail in debian (centos is working fine)
> Fix tests in docker

- t/100-basic.t
- t/api_test.py
- update.py
This resolves issue https://github.com/bootlin/elixir/issues/196
To do that we store each identifier definition in a dictionary where each key is equal to identifier*1 000 000 + line number.
This doesn't seems to slow down update.py so indexing time should remain the same.
However there can be a problem if a file has more than 1 000 000 lines but I think such file doesn't exists so it should be fine.
If this problem occurs, we'll have to multiply the identifier value with an higher power of 10 in the dictionary keys.
> update.py: Filter defs when indexing refs

- docker/debian/Dockerfile
The debian package is outdated so tests fail. Using the pip3 version makes everything work fine.
> docker: debian: Use pip3 version of falcon instead of debian package

- http/style.css
The file listing contains a column for displaying sizes. Directories do not have sizes, as such this section is empty. When a directory entry is hovered, the full width illuminates but only the name section can be clicked. This pull request fixes this. It also fixes it for "parent directory" entries.
**This has only been tested by live-editing pages from the Bootlin instance in a browser, it should be tested before merging.** I do not have a functional local Elixir setup to make sure the stylesheet wasn't broken.
> Front-end: make the whole width of all entries clickable

- api/api.py
- query.py
BUGFIX: Don't double quote DT compatible strings
Both query.py and api.py call parse.quote(ident) which perform
url encoding twice on the identifier. For instance, when
ident="linux,kvm" the first encoding done in api.py changes the
ident to 'wow%2Cey' but the second encoding done in query.py
changes it to 'wow%252Cey' which is no longer valid.
Remove the call to parse.quote on api.py as only one quoting is
necessary, the one in query.py
> BUGFIX: Don't double quote DT compatible strings

- docker/debian/000-default.conf
- docker/debian/Dockerfile
Hello, 
yesterday I tried building Debian image of Elixir. However, the build wouldn't complete due to various errors. In order to fix the Dockerfile, I have done the following changes: 
* Pin base version to debian:bookworm
* Install falcon with apt, install pipx and use pipx to install Pygments - global package installation with pip is not supported anymore
* Update repo permissions and add elixir-data to git safe directories so that git ran from script.sh and cgi stops complaining
* Move apache configuration to an external file for better readability
I also propose (not included in this patch) moving the build args check (lines 5 to 12) to just before git clone of the repo (line 53). 
Currently, if someone builds the image with one project, and then tries to build another image with a …
> Update Debian Dockerfile to Debian Bookworm

- docker/debian/Dockerfile
Fix pygments installation by explicitly excluding pygments from apt install and force installing pygments distribution using pip.
Choice to use `--break-system-packages` is probably controversial, its a rather hacky solution, but since the Dockerfile is single purpose I think it should be fine. 
I couldn't figure out how to properly configure apache cgi to use virtualenv. Per-user installation does not seem like a good choice in this case.
> Fix pygments installation

- http/dynamic-references.js
- http/style.css
- templates/layout.html
Some identifiers can take a really long time to load, depending, among other things, on quality of internet connection. This can result in a confusing situation, where clicking on an identifier seems to do nothing at all, until the popup loads after few seconds. I propose adding a loading indicator which will show up if the API fetch takes more than 200 milliseconds.
I have updated https://elixir.ksi.ii.uj.edu.pl with this branch + a change that adds a random delay to every api call, so that the loading indicator is often visible.
Note: this branch is based on https://github.com/bootlin/elixir/pull/267
>  Show a loading indicator if API fetch takes more than 200 milliseconds 

- http/style.css
to make it more readable because
same units are located on the same column:
```
9 bytes
99999 bytes
instead of
9 bytes
99999 bytes
```
> align size to right

- api/api.py
- data.py
- lib.py
- query.py
Proposed fix to #269 
Refactors the query module into a class to avoid global state and allow for multiple concurrent instances (of the module)
> Refactor query module into a class to avoid global state

- projects/freebsd.sh
Add support for indexing the FreeBSD base repository, found at:
https://cgit.freebsd.org/src/
This contains the FreeBSD kernel plus the base system.
> Support for FreeBSD

- http/autocomplete.py
- http/filters/dtscompB.py
- http/filters/makefiledir.py
- http/filters/makefilefile.py
- http/filters/makefilesrctree.py
- http/web.py
- query.py
- utils/speedtest.py
* Remove query.default_query and all related references
* Pass process env vars to script.sh when ran from Query
To test this, I have:
* Made sure that utils/speedtest.py works
* Ran query.py file and query.py ident 
* Made sure that each filter that was modified ran without errors at least once
* Ran prove (the same tests that failed before my commits still fail, but that's a problem for another PR) 
* Made sure that the server works when LXR_DATA_DIR and LXR_REPO_DIR env vars are not globally set 
This patch is already deployed on https://elixir.ksi.ii.uj.edu.pl/linux/latest/source. This time the the global LXR_* env vars were removed from the container.
> Remove query.default_query and all related references

- static/script.js
- templates/layout.html
@tleb I discovered two bugs in #332: mobile sidebar can't be closed on backdrop click and incorrect desktop sidebar state if page is loaded in mobile mode
> Minor sidebar logic fixes

- README.adoc
I needed to specify `-f` and fix the Dockerfile path while following the README instructions. I'm using Docker version 27.2.1, build 9e34c9b.
> Fix docker build command in README

- script.sh
See commit message.
Fixes #343.
> script.sh: parse-defs: C: index defs that have a CONFIG_ in their line
